name: Church Template CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.ROBOTAPPPEM }}
          APP_ID: ${{ secrets.ROBOTAPP }}

      - name: Get App Installation Token
        run: |
          echo "This token is masked: ${TOKEN}"
        env: 
          TOKEN: ${{ steps.get_token.outputs.app_token }}
